server {
    listen       80;
    listen  [::]:80;
    server_name  _;

    root   /usr/share/nginx/html;
    index  index.html;

    # Páginas servidas tal cual; si no existe el recurso -> 404 personalizado.
    location / {
        try_files $uri $uri/ =404;
    }

    # Página de error 404 de Mazestudio (laberinto).
    error_page 404 /404.html;
    location = /404.html {
        internal;
    }

    # Errores de servidor: usa la 50x.html que trae la imagen base de nginx.
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        internal;
    }
}
